### ISSUE TITLE
Not finding Islands (only picking Patreon islands)

### ISSUE THREAD

**Issue by dkasprick** [ilbuonmarcio/TurnipMaster#3]
I noticed too that it's only finding Patreon islands, this is probably due to the website change I think its defaulting

**Comment by ilbuonmarcio** [comment]
Hi! The website changed, so we will need one additional selection click with the `geckodriver`.

I'll have a look ASAP, meanwhile are you able to find the code changes and submit a PR?
Otherwise I'll get it done by tomorrow evening, not a big problem

**Comment by ilbuonmarcio** [comment]
Fixed as per #4
